version: '3.3'
services:
  database:
    image: postgres
    container_name: database-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
      TZ: America/Recife # Adicione esta linha
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - network-myproject
  node:
    image: 'node:18.16.0'
    container_name: api-container
    working_dir: /usr/src/api
    environment:
      - NODE_ENV=developmnent
      - TZ=America/Recife
    volumes:
      - ./:/usr/src/api
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 768M
        reservations:
          memory: 400M
    networks:
      - network-myproject
    ports:
      - '3000:3000'
    command: sh -c 'npm install && npm run start:dev'
    restart: always
    depends_on:
      - database
volumes:
  db-data-myproject:
  exclude:
networks:
  network-myproject:
    driver: bridge
